detectors:
  UtilityFunction:
    exclude:
      - 'options'
  IrresponsibleModule:
    exclude:
      - 'LoginPage'
      - 'InfPage'
      - 'ModelerPluginsPage'
      - 'MonitoringTemplatesPage'
      - 'AvailableSelectedTableSection'
      - 'DataSourcePopupsSection'
      - 'DataSourcesSection'
      - 'EditDataSourcePointSection'
      - 'EditThresholdSection'
      - 'GraphsDefinitionSection'
      - 'ThresholdsSection'
      - 'ViewEditGraphDefinitionSection'
  TooManyStatements:
    max_statements: 20
  TooManyInstanceVariables:
    max_instance_variables: 10
  DuplicateMethodCall :
    max_calls : 2
  NestedIterators:
    max_allowed_nesting : 2
